### ISSUE TITLE
How to resolve rendering error?

### ISSUE THREAD

**Issue by stack07142** [tiagohm/MosaicCalendarView#1]
I'm creating an app with your MosaicCalendarView.
but, after i create calendar view, I receive this rendering error: "Failed to instantiate one or more classes"

Android Version 2.3.3

![image](https://user-images.githubusercontent.com/23008504/29621940-0fca68e4-885d-11e7-9223-a37d65f51547.png)

![image](https://user-images.githubusercontent.com/23008504/29621999-345b33b4-885d-11e7-864a-26040e9b699f.png)

![image](https://user-images.githubusercontent.com/23008504/29622030-3e890da2-885d-11e7-8c7c-73d2afbca480.png)

Error Message : 

![image](https://user-images.githubusercontent.com/23008504/29621337-6ab3be42-885b-11e7-9966-9906fb8a2757.png)

Exception Details java.lang.ClassCastException: br.tiagohm.mosaiccalendarview.MosaicView$2 cannot be cast to br.tiagohm.mosaiccalendarview.MosaicCalendarView$Adapter   at br.tiagohm.mosaiccalendarview.MosaicCalendarView.getAdapter(MosaicCalendarView.java:104)   at br.tiagohm.mosaiccalendarview.MosaicCalendarView.popularOsDiasDaSemana(MosaicCalendarView.java:113)   at br.tiagohm.mosaiccalendarview.MosaicCalendarView.setWeekTextColor(MosaicCalendarView.java:66)   at br.tiagohm.mosaiccalendarview.MosaicCalendarView.init(MosaicCalendarView.java:53)   at br.tiagohm.mosaiccalendarview.MosaicCalendarView.<init>(MosaicCalendarView.java:35)   at br.tiagohm.mosaiccalendarview.MosaicCalendarView.<init>(MosaicCalendarView.java:30)   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   at android.view.LayoutInflater.inflate(LayoutInflater.java:518)   at android.view.LayoutInflater.inflate(LayoutInflater.java:397) Copy stack to clipboard

**Comment by stack07142** [comment]
I resolved it.
Thank you for sharing this awesome open source.
